# Dockerfile.gpu
# Use a Python 3.10 image with CUDA support
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
    ffmpeg \
    git \
    build-essential \
    wget \
    libgtk2.0-dev \
    libboost-all-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy all files from the build context into the container
COPY . /app

# Install Python packages
RUN pip install --no-cache-dir -r /app/requirements.txt

# Install dlib
RUN pip install dlib==19.24.0

# Install Gunicorn
RUN pip install gunicorn

# Expose port 5000 for Flask
EXPOSE 5000

# Run the Flask app with Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
